workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
      android_signing:
        - keystore_reference
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your@email.com
